name: Add Nong Song
description: Add a Nong song to Auto Nong.
title: "Add Nong Song: "
labels: ["nong-addition", "official-addition"]
body:
  - type: input
    id: song-name
    attributes:
      label: Song Name
      description: What is the name of the song?
      placeholder: ex. Lost (XVA Remix)
    validations:
      required: true
  - type: input
    id: artist-name
    attributes:
      label: Artist Name
      description: Who is the artist of the song?
      placeholder: ex. CRIM3S
    validations:
      required: true
  - type: dropdown
    id: source
    attributes:
      label: Source
      description: Where should the song be sourced from?
      options:
        - Youtube
        - Direct file download
      default: 0
    validations:
      required: true
  - type: input
    id: youtube-link
    attributes:
      label: Youtube Link
      description: If you chose Youtube, what is the URL of the video?
      placeholder: Ex. https://www.youtube.com/watch?v=VZXeoUPPFOY
  - type: input
    id: direct-link
    attributes:
      label: Direct File Link
      description: If you chose Direct file download, what is the URL of the file?
      placeholder: Ex. https://www.example.com/song.mp3
  - type: input
    id: song-id
    attributes:
      label: Song ID
      description: 'Which song ID should the Nong song replace in Geometry Dash? '
      placeholder: ex. 945695
    validations:
      required: true
  - type: markdown
    attributes:
      value: Thanks for contributing songs!

