name: On Comment

on:
  issue_comment:
    types: [created]

jobs:
  on-comment:
    runs-on: ubuntu-latest
    outputs:
      add-nong: ${{ steps.check-comment.outputs.add-nong }}
    steps:
    - name: Check Comment
      id: check-comment
      run: |
        if [ "$(jq -r .comment.body $GITHUB_EVENT_PATH)" = "accept" ]; then
          if [ "$(jq -r .comment.user.login $GITHUB_EVENT_PATH)" = "FlafyDev" ]; then
            echo "Accepting"
            echo "add-nong=true" >> $GITHUB_OUTPUT 
          fi
        fi

  on-comment-adding-nong:
    runs-on: ubuntu-latest
    needs: on-comment
    if: needs.on-comment.outputs.add-nong == 'true'
    steps:
      - uses: ahmadnassri/action-workflow-queue@v1

      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/add-nong-song.yml

      - name: Evaluate Issue
        id: evaluate-issue
        run: ./.github/generate-nong-issue-json.bash

      - name: Generate Issue Message And Commit Details
        id: generate-details
        run: |
          echo "author_name=$(jq -r .issue.user.login $GITHUB_EVENT_PATH)" >> $GITHUB_OUTPUT
          echo "author_email=$(jq -r .issue.user.id $GITHUB_EVENT_PATH)+$(jq -r .issue.user.login $GITHUB_EVENT_PATH)@users.noreply.github.com" >> $GITHUB_OUTPUT

          echo "song_name=$(jq -r .name result.json)" >> $GITHUB_OUTPUT
          echo "artist_name=$(jq -r .artist result.json)" >> $GITHUB_OUTPUT

          cat > body.md << EOF
          Added $(jq -r .name result.json) to Auto Nong ✨
          EOF

      - name: Make Changes
        id: make-changes
        run: |
          jq --argjson newObject "$(cat result.json)" '. += [$newObject]' official.json > temp.json && mv temp.json official.json

      - name: Bot Details
        id: bot-details
        uses: raven-actions/bot-details@v1
        with:
          bot-slug-name: auto-nong

      - name: Add Commit And Push
        uses: EndBug/add-and-commit@v9
        with:
          add: 'official.json'
          author_name: ${{ steps.generate-details.outputs.author_name }}
          author_email: ${{ steps.generate-details.outputs.author_email }}
          committer_name: ${{ steps.bot-details.outputs.name }}
          committer_email: ${{ steps.bot-details.outputs.email }}
          message: |
            official: Add ${{ steps.generate-details.outputs.song_name }} by ${{ steps.generate-details.outputs.artist_name }}

            fixes: #${{ github.event.issue.number }}

      - name: Generate Token
        uses: wow-actions/use-app-token@v2
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }} 

      - name: Create Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body-path: body.md
          token: ${{ steps.generate_token.outputs.BOT_TOKEN }}
